[package]
name = "http"
version = "0.1.4" # remember to update html_root_url
readme = "README.md"
documentation = "https://docs.rs/http"
repository = "https://github.com/hyperium/http"
homepage = "https://github.com/hyperium/http"
license = "MIT/Apache-2.0"
authors = [
  "Alex Crichton <alex@alexcrichton.com>",
  "Carl Lerche <me@carllerche.com>",
  "Sean McArthur <sean@seanmonstar.com>",
]
description = """
A set of types for representing HTTP requests and responses.
"""
keywords = ["http"]
categories = ["web-programming"]

[dependencies]
bytes = "0.4"
fnv = "1.0.5"

[dev-dependencies]
ordermap = "0.3"
quickcheck = "0.5"
rand = "0.3.15"
seahash = "3.0.5"
serde = "1.0"
serde_json = "1.0"

[[bench]]
name = "header_map"
path = "benches/header_map/mod.rs"

[[bench]]
name = "header_value"
path = "benches/header_value.rs"
